const supportedCoins = [
    'AAVE', 'ABBC',  'ADA',  'AERGO', 'AKRO',  'ALEPH',
    'ALGO', 'AMP',   'AMPL', 'ANC',   'ATOM', 'AVAX',  'BAL',
    'BAT',  'BCH',   'BETA', 'BNB',   'BNT',  'BOND',  'BTC',
    'BTT',  'CAKE',  'CARD', 'CBC',   'CELO', 'CFX',   'CHZ',
    'CKB',  'COMP',  'COTI', 'CREAM', 'CRO',  'CRPT',  'CRV',
    'DAG',  'DASH',  'DFI',   'DIVI', 'DODO',  'DOGE',
    'DOT',  'EDG',   'EFX',  'EGLD',  'ELA',  'ENJ',   'EOS',
    'ERN',  'ETC',   'ETH',  'ETN',   'EWT',  'FIL',   'FLOW',
    'FRM',  'FRONT', 'FTM',  'FTT',   'GRIN', 'GRT',   'GTC',
    'HBAR', 'HT',    'ICP',  'IDEX',  'IOST', 'IOTA',  'IOTX',
    'JST',  'KAVA',  'KCS',  'KDA',   'KIN',   'KLAY',
    'KLV',  'KMD',   'KNC',  'LINK',  'LON',  'LRC',   'LTC',
    'LYM',   'MAHA', 'MAN',   'MANA', 'MATIC', 'MIR',
    'MKR',  'NEAR',  'ONE',  'SAND',  'SHIB', 'SOL',   'VET',
    'XMR',  'XRP',   'XTZ'
  ]

const supportedCoinsNames = {
    'AAVE' : "ETHLend",
    'ABBC' : "Alibabacoin",  
    'ADA' : "Cardano",  
    'AERGO' : "Aergo", 
    'AKRO' : "Akropolis",  
    'ALEPH' : "Aleph",
    'ALGO' : "Algorand", 
    'AMP' : "Amp",   
    'AMPL' : "Ampleforth", 
    'ANC' : "Anchor Protocol",   
    'ATOM' : "Cosmos", 
    'AVAX' : "Avalanche",  
    'BAL' : "Balancer",
    'BAT' : "Basic Attention Token",  
    'BCH' : "Bitcoin Cash",   
    'BETA' : "Bet Finance", 
    'BNB' : "Binance Coin",   
    'BNT' : "Bancor Network Token",  
    'BOND' : "BarnBridge",
    'BTC' : "Bitcoin",
    'BTT' : "BitTorrent",  
    'CAKE' : "PancakeSwap",  
    'CARD' : "Cardstack", 
    'CBC' : "CBC.Network",   
    'CELO' : "Celo", 
    'CFX' : "Conflux",   
    'CHZ' : "Chiliz",
    'CKB' : "Nervos Network",  
    'COMP' : "Compound",  
    'COTI' : "Coti", 
    'CREAM' : "Cream Finance", 
    'CRO' : "Cronos",  
    'CRPT' : "Crypterium",  
    'CRV' : "Curve",
    'DAG' : "Constellation",  
    'DASH' : "Dash",  
    'DFI' : "DeFi Chain",   
    'DIVI' : "Divi", 
    'DODO' : "DODO",  
    'DOGE' : "Dogecoin",
    'DOT' : "Polkadot",  
    'EDG' : "Edgeware",   
    'EFX' : "Effect.AI",  
    'EGLD' : "Elrond Network",  
    'ELA' : "Elastos",  
    'ENJ' : "Enjin Coin",   
    'EOS' : "EOS",
    'ERN' : "Ethernity Chain",  
    'ETC' : 'Ethereum Classic',   
    'ETH' : "Ethereum",  
    'ETN' : "Electroneum",   
    'EWT' : "Energy Web Token",  
    'FIL' : "Filecoin",   
    'FLOW' : "Flow",
    'FRM' : "Ferrum Network Token",  
    'FRONT' : "Frontier", 
    'FTM' : "Fantom",  
    'FTT' : "FTX Token",   
    'GRIN' : "Grin", 
    'GRT' : "The Graph",
    'GTC' : "Gitcoin",
    'HBAR' : "Hedera Hashgraph", 
    'HT' : "Huobi Token",    
    'ICP' : "Internet Computer",  
    'IDEX' : "IDEX",  
    'IOST' : "Internet of Services", 
    'IOTA' : "IOTA",  
    'IOTX' : "IoTeX",
    'JST' : "JUST", 
    'KAVA' : "KAVA",  
    'KCS' : "KuCoin Token",  
    'KDA' : "Kadena",   
    'KIN' : "Kin",   
    'KLAY' : "Klaytn",
    'KLV' : "Klever",  
    'KMD' : "Komodo",   
    'KNC' : "Kyber Network",  
    'LINK' : "Chainlink",  
    'LON': "TokenLon Network Token",  
    'LRC' : "Loopring",   
    'LTC' : "Litecoin",
    'LYM' : "Lympo",   
    'MAHA' : "MahaDAO", 
    'MAN' : "Matrix AI Network",   
    'MANA' : "Decentraland", 
    'MATIC' : "Polygon", 
    'MIR' : "Mirror Protocol",
    'MKR' : "MakerDAO",  
    'NEAR' : "Near",  
    'ONE' : "Harmony",  
    'SAND' : "Sandbox",  
    'SHIB' : "Shiba Inu", 
    'SOL' : "Solana",   
    'VET' : "VeChain Token",
    'XMR' : "Monero",  
    'XRP' : "Ripple",   
    'XTZ' : "Tezos"
}


module.exports = {
  supportedCoins,
  supportedCoinsNames
}

